[rfid_cards]

[rfid_cards."0005593265"]
rom_path = "/opt/roms/snes/SuperMarioWorld.zip"
emulator = "/usr/lib/x86_64-linux-gnu/libretro/snes9x_libretro.so"
artwork = "assets/SMWCase.jpg"

[rfid_cards."0007569065"]
rom_path = "/opt/roms/genesis/Sonic.zip"
emulator = "/usr/lib/x86_64-linux-gnu/libretro/genesis_plus_gx_libretro.so"
artwork = "assets/sonic.jpg"
